sudo: false
language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    - stage: test
    - script:
      - yarn run lint
      - yarn test
    - stage: deploy
      script:
      - git config --global user.name "${GH_NAME}"
      - git config --global user.email "${GH_EMAIL}"
      - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
      deploy:
        provider: npm
        email: info@darwineducation.com
        tag: next
        api_key:
          secure: sOTrDUIxh8U0gtCk5gVKEyPjxqahC5NVCOUbCRekD7euzX/o/fgiUajRXQaqFDyPK5kn40iu0gJF4j5yGtHLym+5G2FkxyhGltXmJFmxZHJlt5BwEvPWCLu85ieIV5qO5baNLNC+8GIh3Wtu9XLNQ6lB97DmAZxcBC44HAvOIno3vTeurVvg09bZM6IYISfAGUKUUNkb0ZMMXdlsfrdh8tRolnUkOkvE0McymBZzZqET6xJciPQWAsgqnUizrT3DXKT2ygZ65aZrcX3Oa/MH8NfZTiyjKmU3jRl81oHTwrj5v55wu8aZDrQDguiRiLoAtjjJFUxx5GU2K5XQn+JPYzM0A7pcnrwfHM12oGNwJvVDAYdP7WLwJlc4dEpMqhjGsJrtsxkgVEokmDGr0BBDdzahCQSgdwiymR/ognMuYmve9E6YxwWPnwSVsUet/lrKxWgLvq1IqJnXBfWwWTe05gcCQBe4D1KM/qGQqsC5rySzLXX4DihlliXfC1bodb3PzAHa8VrTup+Zz2GslKm6Ihz0IczTQIqDJAwDE2YaVCyaG945ArKm0nd+pS4uYrkSwk9SwmyIpgpIp5rGEn0zz1jbtFROgPT4iLHwIBnlL6LImUKd6IewyRzAILHhaIN3NX9XnNWKcxoevU781ze7vLRPWCKclYaM2V0e20gBLNE=
stages:
  - test
  - name: deploy
    if: branch = master
notifications:
  email:
    on_success: never
    on_failure: never
